version: "3.2"
services:
  db:
    container_name: goProjectDB
    image: postgres
    restart: always
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
